INSERT INTO criteria (type, category, title, active, sort_order, created_at, updated_at) VALUES
('competency', 'Basic', 'Receive and respond to workplace communication', 1, 1, NOW(), NOW()),
('competency', 'Basic', 'Work with others', 1, 2, NOW(), NOW()),
('competency', 'Basic', 'Demonstrate work values', 1, 3, NOW(), NOW()),
('competency', 'Basic', 'Practice basic housekeeping procedures', 1, 4, NOW(), NOW()),
('competency', 'Common', 'Apply Safety Practices', 1, 5, NOW(), NOW()),
('competency', 'Common', 'Interpret Drawings and Sketches', 1, 6, NOW(), NOW()),
('competency', 'Common', 'Perform Industry Calculations', 1, 7, NOW(), NOW()),
('competency', 'Common', 'Contribute to Quality System', 1, 8, NOW(), NOW()),
('competency', 'Common', 'Use Hand Tools', 1, 9, NOW(), NOW()),
('competency', 'Common', 'Prepare Weld Materials', 1, 10, NOW(), NOW()),
('competency', 'Common', 'Setup Welding Equipment', 1, 11, NOW(), NOW()),
('competency', 'Common', 'Fit up Weld Materials', 1, 12, NOW(), NOW()),
('competency', 'Common', 'Repair Welds', 1, 13, NOW(), NOW()),
('competency', 'Core', 'Weld Carbon Steel Plates Using SMAW', 1, 14, NOW(), NOW()),
('grading', 'Grading', 'Lecture Units (Total Grade)', 1, 1, NOW(), NOW()),
('grading', 'Grading', 'Written Final Exam', 1, 2, NOW(), NOW()),
('grading', 'Grading', 'Skills / Demonstration', 1, 3, NOW(), NOW()),
('grading', 'Grading', 'Class Participation', 1, 4, NOW(), NOW()),
('grading', 'Grading', 'Seat Work', 1, 5, NOW(), NOW()),
('grading', 'Grading', 'Quiz', 1, 6, NOW(), NOW()),
('grading', 'Grading', 'Oral Questioning', 1, 7, NOW(), NOW()),
('grading', 'Grading', 'Skill Demo (Total Grade)', 1, 8, NOW(), NOW()),
('grading', 'Grading', 'Demo', 1, 9, NOW(), NOW()),
('grading', 'Grading', 'Case of studies/projects', 1, 10, NOW(), NOW()),
('grading', 'Grading', 'Total', 1, 11, NOW(), NOW()),
('grading', 'Scale', 'Outstanding (A)', 1, 12, NOW(), NOW()),
('grading', 'Scale', 'Very satisfactory (B)', 1, 13, NOW(), NOW()),
('grading', 'Scale', 'Satisfactory (C)', 1, 14, NOW(), NOW()),
('grading', 'Scale', 'Fair Satisfactory (D)', 1, 15, NOW(), NOW()),
('grading', 'Scale', 'Did not meet expectations', 1, 16, NOW(), NOW()),
('grading', 'Grading', 'Competency Grade', 1, 17, NOW(), NOW()),
('grading', 'Grading', 'Lecture Units (Total Grade)', 1, 18, NOW(), NOW()),
('grading', 'Grading', 'Written Final Exam', 1, 19, NOW(), NOW()),
('grading', 'Grading', 'Skills / Demonstration', 1, 20, NOW(), NOW()),
('grading', 'Grading', 'Class Participation', 1, 21, NOW(), NOW()),
('grading', 'Grading', 'Seat Work', 1, 22, NOW(), NOW()),
('grading', 'Grading', 'Quiz', 1, 23, NOW(), NOW()),
('grading', 'Grading', 'Oral Questioning', 1, 24, NOW(), NOW()),
('grading', 'Grading', 'Task Performance', 1, 25, NOW(), NOW()),
('grading', 'Grading', 'Skill Demo (Total Grade)', 1, 26, NOW(), NOW()),
('grading', 'Grading', 'Demo', 1, 27, NOW(), NOW()),
('grading', 'Grading', 'Case of studies/projects', 1, 28, NOW(), NOW()),
('grading', 'Grading', 'Total', 1, 29, NOW(), NOW()),
('grading', 'Scale', 'Outstanding (A) - 90-100', 1, 30, NOW(), NOW()),
('grading', 'Scale', 'Very satisfactory (B) - 85-89', 1, 31, NOW(), NOW()),
('grading', 'Scale', 'Satisfactory (C) - 80-84', 1, 32, NOW(), NOW()),
('grading', 'Scale', 'Fair Satisfactory (D) - 75-79', 1, 33, NOW(), NOW()),
('grading', 'Scale', 'Did not meet expectations - Below 75', 1, 34, NOW(), NOW());

INSERT INTO criteria (type, category, title, active, sort_order, created_at, updated_at) VALUES
('competency', 'Perform root pass', '1.1 Root pass is performed in accordance with WPS and/or client specifications.', 1, 1, NOW(), NOW()),
('competency', 'Perform root pass', '1.2 Task is performed in accordance with company or industry requirement and safety procedure.', 1, 2, NOW(), NOW()),
('competency', 'Perform root pass', '1.3 Weld is visually checked for defects and repaired, as required.', 1, 3, NOW(), NOW()),
('competency', 'Perform root pass', '1.4 Weld is visually acceptable in accordance with applicable codes and standards.', 1, 4, NOW(), NOW()),
('competency', 'Clean root pass', '2.1 Root pass is cleaned and free from defects and discontinuities.', 1, 1, NOW(), NOW()),
('competency', 'Clean root pass', '2.2 Task is performed in accordance with approved WPS.', 1, 2, NOW(), NOW()),
('competency', 'Weld subsequent/filling passes', '3.1 Subsequent/ filling passes is performed in accordance with approved WPS.', 1, 1, NOW(), NOW()),
('competency', 'Weld subsequent/filling passes', '3.2 Weld visually is checked for defects and repaired, as required.', 1, 2, NOW(), NOW()),
('competency', 'Weld subsequent/filling passes', '3.3 Weld is visually acceptable in accordance with applicable codes and standards.', 1, 3, NOW(), NOW()),
('competency', 'Perform capping', '4.1 Capping is performed in accordance with approved WPS and/or client specifications.', 1, 1, NOW(), NOW()),
('competency', 'Perform capping', '4.2 Weld is visually checked for defects and repaired, as required.', 1, 2, NOW(), NOW()),
('competency', 'Perform capping', '4.3 Weld is visually acceptable in accordance with applicable codes and standards.', 1, 3, NOW(), NOW()),
('competency', 'Defects (Surface Level)', '2.1 Porosity', 1, 1, NOW(), NOW()),
('competency', 'Defects (Surface Level)', '2.2 Undercut', 1, 2, NOW(), NOW()),
('competency', 'Defects (Surface Level)', '2.3 Arc Strike', 1, 3, NOW(), NOW()),
('competency', 'Defects (Surface Level)', '2.4 Spatters', 1, 4, NOW(), NOW()),
('competency', 'Defects (Surface Level)', '2.5 Burn Through', 1, 5, NOW(), NOW()),
('competency', 'Defects (Surface Level)', '2.6 Crater cracks', 1, 6, NOW(), NOW()),
('competency', 'Defects (Surface Level)', '2.7 Cracks', 1, 7, NOW(), NOW()),
('competency', 'Defects (Surface Level)', '2.8 Pinholes/Blowholes', 1, 8, NOW(), NOW()),
('competency', 'Defects (Surface Level)', '2.9 Overlap', 1, 9, NOW(), NOW()),
('competency', 'Defects (Surface Level)', '2.10 Misalignment', 1, 10, NOW(), NOW()),
('competency', 'Defects (Non-Surface Level)', '2.11 Distortion', 1, 1, NOW(), NOW()),
('competency', 'Defects (Non-Surface Level)', '2.12 Slag inclusion', 1, 2, NOW(), NOW()),
('competency', 'Defects (Non-Surface Level)', '2.13 Concavity/convexity', 1, 3, NOW(), NOW()),
('competency', 'Defects (Non-Surface Level)', '2.14 Degree of reinforcement', 1, 4, NOW(), NOW()),
('competency', 'Defects (Non-Surface Level)', '2.15 Lack of Fusion', 1, 5, NOW(), NOW()),
('competency', 'Defects (Non-Surface Level)', '2.16 Under Fill', 1, 6, NOW(), NOW());
